FROM golang:1.26-alpine

RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
    --mount=type=cache,target=/var/lib/apk,sharing=locked \
    apk add --no-cache \
        --repository="https://dl-cdn.alpinelinux.org/alpine/edge/main" \
        --repository="https://dl-cdn.alpinelinux.org/alpine/edge/community" \
        "build-base=0.5-r4" \
        "libheif-dev=1.21.2-r2" \
        "ffmpeg=8.0.1-r3" \
        yt-dlp \
        yt-dlp-ejs \
        yt-dlp-ejs-rt-quickjs

WORKDIR /app

RUN --mount=type=cache,target=/go/pkg/mod \
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.30.0 && \
    go install github.com/air-verse/air@v1.63.1

CMD ["air", "-c", ".air.toml"]